import { ClimbFilter } from "@/lib/types";
import React from "react"; 

export const climbs:ClimbFilter[]= [
    { name: "El Cap Traverse", rating: "4.9", grade: "5.12a", height: "800", type: "Sport", pitches: "7" },
    { name: "Moonlight Buttress", rating: "4.8", grade: "5.12d", height: "1000", type: "Trad", pitches: "10" },
    { name: "North Face Direct", rating: "4.7", grade: "5.10c", height: "500", type: "Trad", pitches: "5" },
    { name: "Granite Glacier Route", rating: "4.6", grade: "5.9", height: "300", type: "Trad", pitches: "3" },
    { name: "Devil's Tower Route", rating: "4.9", grade: "5.11a", height: "850", type: "Trad", pitches: "8" },
    { name: "Half Dome Regular Route", rating: "5.0", grade: "5.13a", height: "900", type: "Trad", pitches: "10" },
    { name: "The Nose", rating: "4.8", grade: "5.12b", height: "990", type: "Trad", pitches: "10" },
    { name: "Zodiac Wall", rating: "4.7", grade: "5.10d", height: "650", type: "Trad", pitches: "6" },
    { name: "Shark's Fin Ridge", rating: "4.5", grade: "5.7", height: "200", type: "Sport", pitches: "2" },
    { name: "Yosemite Falls", rating: "4.4", grade: "5.8", height: "100", type: "Trad", pitches: "1" },
    { name: "The Diamond", rating: "4.9", grade: "5.11d", height: "700", type: "Sport", pitches: "7" },
    { name: "Moraine Ridge Climb", rating: "4.6", grade: "5.10a", height: "320", type: "Trad", pitches: "3" },
    { name: "Desert Solitaire", rating: "4.9", grade: "5.12c", height: "860", type: "Trad", pitches: "9" },
    { name: "Rainbow Wall", rating: "4.9", grade: "5.12a", height: "770", type: "Trad", pitches: "8" },
    { name: "Black Canyon Direct", rating: "4.7", grade: "5.11d", height: "620", type: "Trad", pitches: "6" },
    { name: "Zion's Edge", rating: "4.9", grade: "5.11b", height: "860", type: "Sport", pitches: "9" },
    { name: "Granite Face Traverse", rating: "5.0", grade: "5.13a", height: "999", type: "Trad", pitches: "10" },
    { name: "Falcon's Perch", rating: "4.9", grade: "5.12c", height: "890", type: "Trad", pitches: "9" },
    { name: "Stormy Peak Traverse", rating: "4.8", grade: "5.11b", height: "610", type: "Trad", pitches: "6" },
    { name: "Glacier Vista Route", rating: "5.0", grade: "5.13b", height: "1000", type: "Sport", pitches: "10" },
    { name: "Granite Overhang", rating: "4.7", grade: "5.10b", height: "450", type: "Trad", pitches: "4" },
    { name: "Eagle's Ridge", rating: "4.6", grade: "5.9", height: "600", type: "Sport", pitches: "5" },
    { name: "Whispering Canyon", rating: "4.8", grade: "5.11a", height: "700", type: "Trad", pitches: "6" },
    { name: "Iron Crest", rating: "4.5", grade: "5.8", height: "250", type: "Trad", pitches: "3" },
    { name: "Shadowline Traverse", rating: "4.9", grade: "5.12b", height: "900", type: "Sport", pitches: "9" },
    { name: "Stormy Wall", rating: "4.7", grade: "5.10d", height: "680", type: "Trad", pitches: "6" },
    { name: "Black Hawk Crack", rating: "4.6", grade: "5.9", height: "400", type: "Trad", pitches: "4" },
    { name: "Emerald Pinnacle", rating: "4.8", grade: "5.11c", height: "750", type: "Sport", pitches: "7" },
    { name: "Desert Mirage", rating: "5.0", grade: "5.13a", height: "1000", type: "Trad", pitches: "10" },
    { name: "Falcon's Flight", rating: "4.9", grade: "5.12a", height: "820", type: "Sport", pitches: "8" },
    { name: "Moonlit Ridge", rating: "4.7", grade: "5.10a", height: "480", type: "Trad", pitches: "5" },
    { name: "Sunset Traverse", rating: "4.8", grade: "5.11b", height: "720", type: "Trad", pitches: "7" },
    { name: "Coyote Crack", rating: "4.9", grade: "5.12d", height: "950", type: "Trad", pitches: "9" },
    { name: "Shattered Peak", rating: "4.7", grade: "5.10c", height: "500", type: "Sport", pitches: "5" },
    { name: "Raven's Nest", rating: "4.5", grade: "5.7", height: "200", type: "Trad", pitches: "2" },
    { name: "Ghost Wall", rating: "4.8", grade: "5.11a", height: "650", type: "Trad", pitches: "6" },
    { name: "Windy Pinnacle", rating: "4.6", grade: "5.9", height: "350", type: "Trad", pitches: "3" },
    { name: "Echo Ridge", rating: "4.9", grade: "5.12c", height: "870", type: "Trad", pitches: "9" },
    { name: "Blue Horizon", rating: "4.7", grade: "5.10d", height: "670", type: "Sport", pitches: "6" },
    { name: "Jagged Spire", rating: "4.8", grade: "5.11b", height: "740", type: "Trad", pitches: "7" },
    { name: "Desert Tower", rating: "4.9", grade: "5.12a", height: "880", type: "Trad", pitches: "9" },
    { name: "Cactus Traverse", rating: "4.6", grade: "5.9", height: "400", type: "Trad", pitches: "4" },
    { name: "Wild Horse Ridge", rating: "4.7", grade: "5.10b", height: "550", type: "Trad", pitches: "5" },
    { name: "Thunder Wall", rating: "4.9", grade: "5.12b", height: "910", type: "Trad", pitches: "9" },
    { name: "Crystal Pinnacle", rating: "4.6", grade: "5.8", height: "280", type: "Sport", pitches: "3" },
    { name: "Copper Ridge", rating: "4.8", grade: "5.11c", height: "770", type: "Trad", pitches: "7" },
    { name: "Storm King Arête", rating: "4.7", grade: "5.10c", height: "620", type: "Trad", pitches: "6" },
    { name: "Iron Veil Traverse", rating: "5.0", grade: "5.13a", height: "1000", type: "Sport", pitches: "10" },
    { name: "Shadow Canyon", rating: "4.7", grade: "5.10b", height: "570", type: "Trad", pitches: "5" },
    { name: "Twilight Spire", rating: "4.8", grade: "5.11a", height: "680", type: "Sport", pitches: "6" },
    { name: "Red Rock Traverse", rating: "4.9", grade: "5.12c", height: "880", type: "Sport", pitches: "9" },
    { name: "Lost Horizon", rating: "4.8", grade: "5.11b", height: "720", type: "Trad", pitches: "7" },
    { name: "Crested Ridge", rating: "4.7", grade: "5.10d", height: "590", type: "Sport", pitches: "5" },
    { name: "Diamond Edge", rating: "4.9", grade: "5.12a", height: "850", type: "Trad", pitches: "8" },
    { name: "Granite Skyway", rating: "5.0", grade: "5.13b", height: "1000", type: "Trad", pitches: "10" },
    { name: "Iron Horse Arête", rating: "4.8", grade: "5.11c", height: "750", type: "Trad", pitches: "7" },
    { name: "Echo Pinnacle", rating: "4.7", grade: "5.10c", height: "620", type: "Trad", pitches: "6" },
    { name: "Whispering Ridge", rating: "4.9", grade: "5.12d", height: "950", type: "Sport", pitches: "9" },
    { name: "Desert Vista Wall", rating: "4.7", grade: "5.10a", height: "480", type: "Trad", pitches: "5" },
    { name: "Windy Spire", rating: "4.8", grade: "5.11b", height: "730", type: "Trad", pitches: "7" },
    { name: "Granite Moonwall", rating: "4.9", grade: "5.12c", height: "900", type: "Sport", pitches: "9" },
    { name: "Storm Ridge Arête", rating: "4.8", grade: "5.11a", height: "680", type: "Trad", pitches: "6" },
    { name: "Copper Canyon", rating: "4.7", grade: "5.10d", height: "610", type: "Trad", pitches: "6" },
    { name: "Echo Wall Traverse", rating: "5.0", grade: "5.13a", height: "1000", type: "Trad", pitches: "10" },
    { name: "Silver Pinnacle", rating: "4.7", grade: "5.10c", height: "540", type: "Trad", pitches: "5" },
    { name: "Raven's Crest", rating: "4.6", grade: "5.9", height: "370", type: "Trad", pitches: "4" },
    { name: "Iron Mirage", rating: "5.0", grade: "5.13b", height: "1000", type: "Trad", pitches: "10" },
    { name: "Falcon's Peak", rating: "4.8", grade: "5.11b", height: "710", type: "Trad", pitches: "7" },
    { name: "Crystal Veil", rating: "4.7", grade: "5.10a", height: "490", type: "Trad", pitches: "5" },
    { name: "Thunderhead Arête", rating: "4.9", grade: "5.12d", height: "960", type: "Trad", pitches: "9" },
    { name: "Wild Horizon", rating: "4.8", grade: "5.11c", height: "730", type: "Trad", pitches: "7" },
    { name: "Shadow Spire", rating: "4.6", grade: "5.9", height: "410", type: "Trad", pitches: "4" },
    { name: "Coyote Arête", rating: "4.7", grade: "5.10d", height: "600", type: "Sport", pitches: "6" },
    { name: "Jagged Wall", rating: "4.8", grade: "5.11a", height: "670", type: "Trad", pitches: "6" },
    { name: "Stormy Ridge", rating: "4.9", grade: "5.12c", height: "910", type: "Trad", pitches: "9" },
    { name: "Copper Traverse", rating: "4.6", grade: "5.8", height: "340", type: "Sport", pitches: "3" },
    { name: "Nightfall Crag", rating: "4.9", grade: "5.12b", height: "930", type: "Trad", pitches: "9" },
    { name: "Iron Ridge", rating: "4.7", grade: "5.10a", height: "480", type: "Trad", pitches: "4" },
    { name: "Desert Spire", rating: "4.8", grade: "5.11c", height: "740", type: "Trad", pitches: "7" },
    { name: "Wildcat Arête", rating: "4.9", grade: "5.12a", height: "870", type: "Trad", pitches: "8" },
    { name: "Emerald Wall", rating: "4.7", grade: "5.10d", height: "600", type: "Trad", pitches: "6" },
    { name: "Shattered Pinnacle", rating: "5.0", grade: "5.13b", height: "1000", type: "Trad", pitches: "10" },
    { name: "Whispering Edge", rating: "4.8", grade: "5.11b", height: "710", type: "Trad", pitches: "7" },
    { name: "Granite Gateway", rating: "4.9", grade: "5.12d", height: "950", type: "Trad", pitches: "9" },
    { name: "Cactus Wall", rating: "4.7", grade: "5.10c", height: "580", type: "Trad", pitches: "5" },
    { name: "Echo Horizon", rating: "4.9", grade: "5.12b", height: "900", type: "Trad", pitches: "9" },
    { name: "Wild Horse Spire", rating: "4.8", grade: "5.11c", height: "730", type: "Trad", pitches: "7" },
    { name: "Iron Veil", rating: "4.7", grade: "5.10b", height: "540", type: "Trad", pitches: "5" },
    { name: "Twilight Arête", rating: "4.9", grade: "5.12a", height: "880", type: "Trad", pitches: "8" },
    { name: "Copper Moonwall", rating: "4.7", grade: "5.10a", height: "480", type: "Sport", pitches: "4" },
    { name: "Lost Pinnacle", rating: "4.8", grade: "5.11d", height: "780", type: "Trad", pitches: "7" },
    { name: "Thunder Spire", rating: "5.0", grade: "5.13a", height: "1000", type: "Trad", pitches: "10" },
    { name: "Emerald Ridge", rating: "4.9", grade: "5.12c", height: "930", type: "Sport", pitches: "9" },
    { name: "Crystal Wall", rating: "4.8", grade: "5.11a", height: "700", type: "Trad", pitches: "7" },
    { name: "Desert Vista", rating: "4.6", grade: "5.9", height: "370", type: "Trad", pitches: "4" },
    { name: "Raven's Flight", rating: "4.9", grade: "5.12b", height: "920", type: "Trad", pitches: "9" },
    { name: "Granite Crown", rating: "4.8", grade: "5.11c", height: "750", type: "Trad", pitches: "7" },
    { name: "Blue Mirage", rating: "4.7", grade: "5.10d", height: "620", type: "Trad", pitches: "6" },
    { name: "Whispering Arête", rating: "5.0", grade: "5.13b", height: "1000", type: "Sport", pitches: "10" },
    { name: "Stormy Spire", rating: "4.9", grade: "5.12d", height: "970", type: "Sport", pitches: "9" },
    { name: "Nightfall Ridge", rating: "4.7", grade: "5.10a", height: "500", type: "Trad", pitches: "5" },
    { name: "Iron Traverse", rating: "4.9", grade: "5.12c", height: "910", type: "Sport", pitches: "9" },
  ];